#spring.application.name=User
#server.port=${PORT:8080}
#server.address=0.0.0.0
#
#spring.datasource.url=jdbc:mysql://maglev.proxy.rlwy.net:25712/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=LXEAZEBLNAPqwcnGFFXFfvlxfdeRancZ
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
#springdoc.api-docs.enabled=true
#springdoc.swagger-ui.csrf.enabled=true
#
#spring.servlet.multipart.max-file-size=50MB
#spring.servlet.multipart.max-request-size=50MB
#
#brevo.api.key=${SENDINBLUE_API_KEY}
spring.application.name=User
server.port=${PORT:8080}
server.address=0.0.0.0

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.csrf.enabled=true

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

brevo.api.key=${BREVO_API_KEY}
brevo.from.email=kisanseva.noreply@gmail.com
brevo.from.name=Kisan Seva
