spring.application.name=User
server.port=10000
server.address=0.0.0.0

spring.datasource.url=jdbc:postgresql://db.ezjekakvqdwprsrtczrh.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=Yj$!jC+4sYFjNX&

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
