spring.application.name=User
server.port=1012
server.address=0.0.0.0
spring.datasource.url=jdbc:mysql://localhost:3306/User
spring.datasource.username=root
spring.datasource.password=rpmanna45
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

springdoc.api-docs.enabled=true
springdoc.swagger-ui.csrf.enabled=true

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB